### ISSUE TITLE
[feature] Use zsh's math calculation to replace bc

### ISSUE THREAD

**Issue by Freed-Wu** [bigH/auto-sized-fzf#1]
This zsh plugin has a dependency `bc`. However, zsh has its math calculation function, even has a `zcalc` which can replace `bc`. How about removing dependency `bc`?

```
❯ autoload -Uz zcalc
❯ zcalc
1> 1 + 1
2
2>
```

**Comment by bigH** [comment]
Depending on `bc` seems worse than depending on `zcalc`. `bc` is a system utility available on most linux/unix installations that humans would use. Where-as someone has to select `zsh` as their shell to make `zcalc` available.

Since this script is meant to be sourced, it should be at least shell agnostic.

**Comment by Freed-Wu** [comment]
Oh :cry: sorry, I thought incorrectly that it is a zsh plugin.

**Comment by bigH** [comment]
All good. Hope you enjoy :)
